### ISSUE TITLE
Outdated script at homepage

### ISSUE THREAD

**Issue by johnd0e** [pcaddict08/Phtiv-Draw-Tools#9]
http://wasabee.rocks/ and http://phtiv.com/# contain outdated version of script.

- `@updateURL    http://wasabee.rocks/wasabee.meta.js`
   `wasabee.meta.js` here points to nonexistent http://phtiv.com/phtivdrawtools/*
- `@downloadURL  http:/wasabee.rocks/wasabee.user.js` 
   should be 2 slashes after `http:`
- wrapper part is not completely correct, you can see it in About IITC
  but in [sources](https://github.com/pcaddict08/Wasabee-IITC/tree/master/src/wrapper) all is fine, so I suppose wasabee.rocks hosts outdated version

**Comment by cloudkucooland** [comment]
@johnd0e can you switch over to https://github.com/wasabee-project/Wasabee-IITC/issues , this tree has been merged into that larger project. I'd appreciate testing on the dev code if you have the time.

**Comment by johnd0e** [comment]
OK, thank you for pointing that out.

But this report is not about code.
Is http://wasabee.rocks/ correct place where built script deployed?

**Comment by cloudkucooland** [comment]
Yes, the released version of the script lives at that URL.

**Comment by johnd0e** [comment]
OK, it would be great to update it to current sources.

**Comment by cloudkucooland** [comment]
We are in the middle of some major reworking on it. The current development version is getting close, but is not release quality. We can't "update it to current sources" until it is release quality. Helpful testing of the development version would make the process of getting it release-ready go faster.

**Comment by johnd0e** [comment]
OK, I thank you for explanation.

Should I built it from sources? Or use some prebuilt version?

**Comment by cloudkucooland** [comment]
ping me on telegram (@deviousness) and I'll give you a URL to the up-to-the-minute build

**Comment by phtiv** [comment]
This repo is deprecated and is an older version of the script.  This weekend I'm planning on updating the wasabee.rocks sites and will point them to the most up to date user/meta scripts.  closing this for now.
